### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by houshuang** [acowley/Frames#1]
I would love some more examples, as I struggle to understand the types and the setup here, for example:

- how do I request a row by number/id
- how do I request a row where col A conforms to some predicate
- etc. 

Here are some of the things I listed on sdiehl/frame:
> - selecting rows based on a single column predicate (the equivalent of 
> db[db$age > 30,] in R) 
> - selecting rows based on multiple column predicates (the equivalent of 
> db[db$age > 30 && db$weight >50,]) 
> - creating a new hframe where a row has been modified by a function 
> (equivalent of db$age = db$age * 2, but functionally) - or something like 
> newframe 
> = fmap (* 2) (frame ! "age") 
> - creating a new hframe with an added column calculated based on one or 
> more existing columns (the equivalent of db$derived = db$age / db$weight, 
> but functionally) 
> - an example of groupBy 

however he had already provided examples of the basics above (getting a column, transforming it by a function etc).

The current examples are either very simple (printing a table), or fairly involved.

Anything at all would be helpful, thanks!

**Comment by houshuang** [comment]
I keep meaning to do this, in the meantime here are some very simple examples in Julia, R and Python: http://ajkl.github.io/Dataframes/

**Comment by acowley** [comment]
There are now a [port](http://acowley.github.io/Frames) of that document, and plotting examples in the repository. Thanks for the pointer to that page!
