### ISSUE TITLE
Plot demo doesn't work (even after getdata succeeds). 

### ISSUE THREAD

**Issue by michaelochurch** [acowley/Frames#11]
It seems to be failing on the nonexistence of a local file that it expects the ```getdata``` task to generate. The error is this:

```
pwnmachine $ cabal run plot
Preprocessing library Frames-0.1.0.0...
In-place registering Frames-0.1.0.0...
Preprocessing executable 'plot' for Frames-0.1.0.0...
[1 of 1] Compiling Main             ( demo/Plot.hs, dist/build/plot/plot-tmp/Main.o )
Loading package ghc-prim ... linking ... done.
[...]
Loading package Chart-diagrams-1.3.3 ... linking ... done.

demo/Plot.hs:1:1:
    Exception when trying to run compile-time code:
      data/trigly_d.csv: openFile: does not exist (No such file or directory)
    Code: tableTypes "Trigly" "data/trigly_d.csv"
```

**Comment by acowley** [comment]
Shoot, this may have been a data file that required a bit of work to extract (ie a short python program using a library to convert the format).

I'm wary of redistributing the data, so we'll either need to figure out how to extract the data without incurring any heavy dependencies, or switch that demo to use a different data set.

**Comment by acowley** [comment]
I added this file to the repository in lieu of a better solution.
