### ISSUE TITLE
Trouble creating methods for general records

### ISSUE THREAD

**Issue by miguelfdag** [acowley/Frames#122]
Hi,

I am trying to make simple operations with a Frame, the problem that I have is that I want the Frame to be as general as possible. For example, I want to create a function that returns true if the value of the field is equal to a parameter:

```haskell
checkEquals :: (Eq a) => Record (s :-> a ': rs) -> a -> Bool
checkEquals (h :& t) val = t == val
```
But I am getting the following error:
```
Couldn't match expected type ‘Rec Identity rs’
                  with actual type ‘a’
      ‘a’ is a rigid type variable bound by
        the type signature for:
          checkEquals :: forall a (s :: ghc-prim-0.5.0.0:GHC.Types.Symbol) (rs :: [*]).
                         Eq a =>
                         Record (s :-> a : rs) -> a -> Bool
```

The example I am trying is a one column frame, I do not know if it makes a difference.

Cheers.

**Comment by acowley** [comment]
I’m sorry this Issue slipped off my list. I hope you were able to figure out the problem.
