### ISSUE TITLE
Efficient way to get to whatever the value may be

### ISSUE THREAD

**Issue by o1lo01ol1o** [acowley/Frames#124]
Given `ColFun Maybe MyLargeRow`, as I'm thinking through some reasonably complex comparisons on values, I find that I'm using the following pattern:

```haskell
case (toHKD . rget @ColumnHeader) row of
  Just val ->case (toHKD. rget @OtherTHing) row of
       Just val2 -> 
  [...]
```
Is this the intended way to go about it?  It seems to be making `haskell-ide-engine` very slow and sad  (I had to set -freduction-depth=0 to get my row type to be inferred, so this may have something to do with it).

**Comment by acowley** [comment]
If I'm understanding correctly, I use `rcast` for this type of thing. [This example](https://github.com/acowley/Frames/blob/master/test/UncurryFold.hs#L16) may be relevant.

**Comment by o1lo01ol1o** [comment]
I can indeed cast to a subset of columns first, I imagine this will help things.  But is `toHKD. rget @Foo` the intended way of gettting the value of `@Foo` in `ColFun Maybe [Foo, Bar]` ?

**Comment by acowley** [comment]
It depends a bit on the interpretation functor in place. I usually use `ElField`, so I use [`rvalf`](https://github.com/VinylRecords/Vinyl/blob/a69915a6ed2460793b7b77bec80bab4516885a8f/Data/Vinyl/Derived.hs#L85) quite a bit ([an example](https://github.com/acowley/Frames/blob/master/test/Categorical.hs#L22)).

**Comment by o1lo01ol1o** [comment]
Right, ok.  There are a few answers, then.  Just trying to think about how someone who's never used Frames might deal with this particular problem.  Thanks.

**Comment by acowley** [comment]
If you're not using `OverloadedLabels`, then there is [`rgetX`](https://github.com/VinylRecords/Vinyl/blob/master/tests/XRecSpec.hs#L45) which I think is the most direct answer to your question (sorry it took me this many tries to get there :P ).
