### ISSUE TITLE
Show instance / printing functions for Frame?

### ISSUE THREAD

**Issue by chfin** [acowley/Frames#130]
It would be nice to have a `Show` instance for Frames, or at least a function to quickly print a frame manually.

I'm currently using something like this:
```haskell
showRow :: (RecMapMethod Show ElField a, RecordToList a)
        => (Record a) -> String
showRow row = intercalate "\t" $ showFields row

showHeader :: forall a . (ColumnHeaders a) => Frame (Record a) -> String
showHeader frame = intercalate "\t" $ columnHeaders (Proxy :: Proxy (Record a))

viewFrame :: (RecMapMethod Show ElField a, RecordToList a, ColumnHeaders a)
          => Frame (Record a) -> IO ()
viewFrame frame = do
  putStrLn $ showHeader frame
  mapM_ (putStrLn . showRow) frame
```

This could be easily turned into a `Show` instance or a handful of manual showing functions.
Having `Show` would be easier to use, but lacks a corresponding `Read` instance.
Some kind of `preview` that only shows a limited number of rows might also be useful.

If you want, I can prepare a pull request.

**Comment by teto** [comment]
I was looking for similar functions to troubleshoot an issue so it's a yes from me but I am no maintainer.

**Comment by acowley** [comment]
Yeah, I don't know how this isn't there already! I guess `pipePreview` was serving that role, but it's not nearly obvious enough. Is the `IO ()` type on `viewFrame` the best option or should we return a list of lines to make it easier to `take` a prefix?

**Comment by acowley** [comment]
I took a [whack](https://github.com/acowley/Frames/commit/03387e8436a395064f83d40ffc4950332039da16) at this. Let me know if there are any suggestions!

**Comment by acowley** [comment]
I've pushed these in the 0.7.1 release. I hope they are helpful!
