### ISSUE TITLE
tableTypes shadows Prelude.zip when "zip" column is in CSV

### ISSUE THREAD

**Issue by MMesch** [acowley/Frames#138]
I am loading a csv file with a column that is called `zip` with Frames in an ihaskell jupyter notebook. `tableTypes` then shadows `Prelude.zip`. How would you deal with this situation?

**Comment by acowley** [comment]
You can name the columns yourself, or use `tablePrefix` to specify a prefix for each generated name. Perhaps this [example](http://acowley.github.io/Frames/#orgfa57664) is close enough to your situation.

**Comment by MMesch** [comment]
Great, thank you!
