### ISSUE TITLE
Multiple declarations from the same line of code when compiling

### ISSUE THREAD

**Issue by gregnwosu** [acowley/Frames#140]
![image](https://user-images.githubusercontent.com/193151/70462948-d8faba80-1ab3-11ea-8cb2-764499fb607b.png)

**Comment by acowley** [comment]
Thanks for the report! Is `BbMxGG3` something from a header row of a CSV file you're dealing with?

**Comment by gregnwosu** [comment]
yes it is , I actually traced this down to having more data columns than header columns! so not  rreally a bug in frames but a better error message might be useful
