### ISSUE TITLE
Move away from the discrimination dependency?

### ISSUE THREAD

**Issue by acowley** [acowley/Frames#143]
The `discrimination` package doesn’t build with GHC 8.8. I’ve had a [PR](https://github.com/ekmett/discrimination/pull/22) open for about four months now with no movement, so we should think about finding another solution. What would make sense as an alternative implementation strategy? Cc @cfhammill

**Comment by cfhammill** [comment]
Hmm, that's unfortunate. I'm not particularly keen on rewriting the join logic, although it probably wouldn't be terrible if necessary. I wonder if we could reach out to @ekmett and request commit rights for one of us? Alternatively there's a custom vinyl submodule in Frames, we could employ a similar strategy for discrimination.

**Comment by ekmett** [comment]
I'm happy to give you commit and hackage push rights to discrimination. Sorry I've been a bad maintaintainer lately.

**Comment by ekmett** [comment]
I've given @acowley direct access to the main discrimination repo, and to the hackage maintainer group, and pushed out a revision to 0.4 allow the current hashable. (the primitive revision was already up)

**Comment by acowley** [comment]
Thank you @ekmett!

**Comment by cfhammill** [comment]
Great, thanks @ekmett and @acowley!
