### ISSUE TITLE
Illegal data constructor name: ‘FooBarCinco De Mayo

### ISSUE THREAD

**Issue by o1lo01ol1o** [acowley/Frames#145]
When trying to infer some categorical columns, it seems like the TH should do some basic sanitizing before trying to create ctors?

`tableTypes' (rowGenCat "data/foo.csv") { rowTypeName = "Foo", tablePrefix = "C" }`

The actual entry is : `Cinco De Mayo`

**Comment by acowley** [comment]
Huh, the intention was that [this function](https://github.com/acowley/Frames/blob/master/src/Frames/TH.hs#L44) was catching that sort of thing. Either it doesn't do what it's supposed to, or it's not getting called.

**Comment by o1lo01ol1o** [comment]
addressed by #146
