### ISSUE TITLE
writeCSV should accept ParserOptions

### ISSUE THREAD

**Issue by teto** [acowley/Frames#155]
to be consistent with csv reading.
I would like to test that serializing/deserializing of my CSV files work ok but the inital file has a different delimitor than "," because fields themselves have `,` (I use `|` as a delimiter).
I can do the PR if you tell me what you prefer:
- change writeCSV inplace
- introduce a new function (but under what name ?)

**Comment by acowley** [comment]
We should have a general function that takes the options, or at least the separator string, and keep `writeCSV` with precisely the same type and functionality, but have its implementation call the new more general function.

**Comment by teto** [comment]
closed by linked issue

**Comment by teto** [comment]
huh no, fixed in https://github.com/acowley/Frames/pull/156 .
