### ISSUE TITLE
README: column-oriented v. array of structures

### ISSUE THREAD

**Issue by ulysses4ever** [acowley/Frames#159]
README reads:

>  load that data into column-oriented storage in memory (an in-core array of structures (AoS)).

Tell me if I'm wrong but I think that column-oriented format is, to the contrary, SoA (we store several columns). So there's a contradiction here, or?..

**Comment by acowley** [comment]
You’re right! It’s badly worded. I think the issue is that we’re providing a convenient AoS API atop the column storage. We also have an SoA that gives a record with fields that are arrays. I’d welcome help in rewording that, or I can take a crack at it.

**Comment by ulysses4ever** [comment]
Oh, I see, thanks for answering! Not sure I have great suggestions here but how about:

> We generate a collection of definitions generated by inspecting the data file at compile time (using tableTypes), then, at runtime, load that data into column-oriented storage in memory with a row-oriented interface (an in-core array of structures (AoS)).

**Comment by acowley** [comment]
That’s an improvement! If you’re willing, please do open a PR as I may not get any keyboard time today.

**Comment by ulysses4ever** [comment]
Here you go: #160
