### ISSUE TITLE
cabal: Cannot build the executable 'getdata' because the component is marked as disabled in the .cabal file.

### ISSUE THREAD

**Issue by gxr** [acowley/Frames#17]
I am checking out Frames and I'm trying the command 
'cabal run getdata'. When I do so I get the error "cabal: Cannot build the executable 'getdata' because the component is marked as disabled in the .cabal file." I opened up Frames.cabal and noticed that it's some flag. I am new to Haskell so I'm not sure how to set the flag for demos to true.

I've tried cabal run -f demos getdata.

Thanks.

**Comment by acowley** [comment]
Can you try running `cabal configure -f demos` before running `cabal run getdata`?

**Comment by gxr** [comment]
That works, thanks.
