### ISSUE TITLE
no 0.7.4 tag ?

### ISSUE THREAD

**Issue by teto** [acowley/Frames#183]
I noticed you dropped the htoml dependency (cool, it was unmaintained). The changelog contains an entry for 0.7.4 but the git tags stop at 0.7.1, could you update those please ?

**Comment by acowley** [comment]
I apologize, I dropped the ball on tagging those. Since current `main` is on package as 0.7.4.2, I've tagged that revision. Is that enough to get things un-stuck, or do you need a 0.7.4 tag, too?

**Comment by teto** [comment]
I've been using HEAD thanks for the tag !
