### ISSUE TITLE
Strictness of value in CoRec

### ISSUE THREAD

**Issue by meiersi** [acowley/Frames#19]
The `Rec` type in `vinyl` is [strict both in the value and the tail](http://hackage.haskell.org/package/vinyl-0.5.1/docs/Data-Vinyl-Core.html#t:Rec). I think that is a good decision, as it simplifies reasoning about the space usage of `Rec`s. Do you have a particular reason why you make the value in a `CoRec` non-strict?

(PS: Thanks for this library. It's sources are a very interesting and enlightening read!)

**Comment by acowley** [comment]
No reason; that should be fixed. I'll accept a PR, or do it myself when I get some cycles. 

Thanks for the kind words!
