### ISSUE TITLE
Can't install demos

### ISSUE THREAD

**Issue by jdreaver** [acowley/Frames#23]
I tried to run `cabal install --dependencies-only -f demos` in a new sandbox, and cabal threw an error. I think this is because of the recent update of `diagrams` to version 1.3. I think this could be fixed by specifying version ranges for each dependency in the demos, but I am not sure what versions to use. 

Here is the output of the command:
```
$ cabal install --dependencies-only -f demos

Resolving dependencies...
cabal: Could not resolve dependencies:
trying: Frames-0.1.0.0 (user goal)
rejecting: Frames-0.1.0.0:-demos (global constraint requires opposite flag
selection)
trying: Frames-0.1.0.0:+demos
trying: diagrams-lib-1.3 (dependency of Frames-0.1.0.0:+demos)
trying: diagrams-core-1.3 (dependency of diagrams-lib-1.3)
next goal: Chart-diagrams (dependency of Frames-0.1.0.0:+demos)
rejecting: Chart-diagrams-1.4, 1.3.3, 1.3.2, 1.3.1, 1.3, 1.2.4, 1.2.3
(conflict: diagrams-core==1.3, Chart-diagrams => diagrams-core>=1.2 && <1.3)
rejecting: Chart-diagrams-1.2.2 (conflict: diagrams-core==1.3, Chart-diagrams
=> diagrams-core>=1.1 && <1.2)
rejecting: Chart-diagrams-1.2 (conflict: diagrams-core==1.3, Chart-diagrams =>
diagrams-core>=0.7 && <1.2)
rejecting: Chart-diagrams-1.1 (conflict: diagrams-core==1.3, Chart-diagrams =>
diagrams-core>=0.7 && <0.8)
rejecting: Chart-diagrams-1.0 (conflict: diagrams-core==1.3, Chart-diagrams =>
diagrams-core>=0.7 && <1.0)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

**Comment by acowley** [comment]
Darn. It looks like `Chart-diagrams` has an [issue](https://github.com/timbod7/haskell-chart/issues/80) to track this, so we either help fix that or upper bound the demos. [Investigation in progress]

**Comment by jdreaver** [comment]
The next highest version for the diagrams libs are as follows:

```
diagrams-core == 1.2.0.6
diagrams-lib == 1.2.0.9
diagrams-rasterific == 0.1.0.8
```

Unfortunately, I am on GHC 7.10.1, which has `base==4.8.0`, and those package versions require `base < 4.8`. Setting those versions as upper limits could possibly fix the examples for older GHC versions, however.

By the way, thanks for developing this package! I've begun using financial time series in Haskell after being a loyal Python/pandas users for years. A good Frame-like object is very helpful in data analysis.

**Comment by acowley** [comment]
I finished the PR for `Chart-diagrams` yesterday, and got `diagrams-svg` to fix something to enable the `Chart` update to work. If you're eager, you can use this [branch](https://github.com/acowley/haskell-chart/tree/Fix80) of my `haskell-chart` fork until it gets merged upstream.

**Comment by jdreaver** [comment]
Wow, that was quick! Thanks!

**Comment by sebeaumont** [comment]
So the Frames master demos should build against haskell-chart Fix80 branch?

**Comment by acowley** [comment]
Something seems to be going wrong with what `.cabal` file is being used there. The new `Chart-diagrams` `.cabal` file has the constraint `diagrams-postscript >= 1.3 && < 1.4`.

**Comment by sebeaumont** [comment]
Thanks. I'll dig into it later might be git...

**Comment by sebeaumont** [comment]
Only thing I can see is:
```chart-tests/Chart-tests.cabal``` has a constraint ```diagrams-postscript    >= 0.7 && < 1.2```

**Comment by acowley** [comment]
The way I worked on that branch was to clone the Chart fork into the directory with my Frames sandbox, then `cabal sandbox add-source chart/Chart-diagrams`, and then configure and build Frames (ie `cabal configure -f demos` then `cabal run plot`). So everything is from hackage except `Chart-diagrams`. Is that how you're trying it, too?

**Comment by sebeaumont** [comment]
I've tried just building the haskell-chart in its own sandbox to get the problem above -- which makes no sense since the constraints seem right. I'll try again with Frames and the add-source... ah I was adding the whole of haskell-diagrams... hold on

**Comment by sebeaumont** [comment]
I'm trying this:
```
cabal sandbox init
cabal sandbox add-source  ../haskell-chart/chart-diagrams
cabal install --dependencies-only -f demos
```
and I get this now...
```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: Frames-0.1.0.0 (user goal)
rejecting: Frames-0.1.0.0:-demos (global constraint requires opposite flag
selection)
trying: Frames-0.1.0.0:+demos
trying: diagrams-lib-1.3.0.1 (dependency of Frames-0.1.0.0:+demos)
trying: lens-4.11 (dependency of diagrams-lib-1.3.0.1)
trying: diagrams-core-1.3.0.1 (dependency of diagrams-lib-1.3.0.1)
next goal: Chart-diagrams (dependency of Frames-0.1.0.0:+demos)
rejecting: Chart-diagrams-1.4 (conflict: lens==4.11, Chart-diagrams =>
lens>=3.9 && <4.10)
rejecting: Chart-diagrams-1.3.3, 1.3.2, 1.3.1, 1.3, 1.2.4, 1.2.3 (conflict:
diagrams-core==1.3.0.1, Chart-diagrams => diagrams-core>=1.2 && <1.3)
rejecting: Chart-diagrams-1.2.2 (conflict: diagrams-core==1.3.0.1,
Chart-diagrams => diagrams-core>=1.1 && <1.2)
rejecting: Chart-diagrams-1.2 (conflict: diagrams-core==1.3.0.1,
Chart-diagrams => diagrams-core>=0.7 && <1.2)
rejecting: Chart-diagrams-1.1 (conflict: diagrams-core==1.3.0.1,
Chart-diagrams => diagrams-core>=0.7 && <0.8)
rejecting: Chart-diagrams-1.0 (conflict: diagrams-core==1.3.0.1,
Chart-diagrams => diagrams-core>=0.7 && <1.0)
Backjump limit reached (change with --max-backjumps).
```

**Comment by idontgetoutmuch** [comment]
I am guessing you are using 7.10, I think chart-diagrams is currently broken. I can't the ticket right now.

**Comment by sebeaumont** [comment]
yup 7.10 all the way

**Comment by acowley** [comment]
@sebeaumont We're really suffering here from the need for the fork of Chart. I've bumped the lens bounds, and now if I `add-source` both `chart` and `chart-diagrams`, I can build from a clean start again. So you'll need to fetch and reset your clone of the [Fix80](https://github.com/acowley/haskell-chart/tree/Fix80) branch.

I hope this gets resolved soon.

**Comment by sebeaumont** [comment]
Thanks for the help -- I'm up and running now.
Let's hope this gets merged soon.

**Comment by cocreature** [comment]
`Chart-1.5` and `Chart-diagrams-1.5` are out supporting `diagrams-1.3` so it's now possible to build using only packages on hackage. I guess that also could justify finally releasing `Frames` on hackage :)

**Comment by acowley** [comment]
Thanks for the nudge @cocreature! I'd been checking every couple days waiting for the new `Chart` packages to go up.

**Comment by mittenchops** [comment]
I understand this could be a pain, but any chance a version could be made that's backwards compatible with the haskell-platform that's in the ubuntu 14.04 repos?  

```
$ cabal install --dependencies-only -f demos
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: Frames-0.1.2.1 (user goal)
next goal: base (dependency of Frames-0.1.2.1)
rejecting: base-4.6.0.1/installed-8aa... (conflict: Frames => base>=4.7 &&
<4.9)
rejecting: base-4.8.2.0, 4.8.1.0, 4.8.0.0, 4.7.0.2, 4.7.0.1, 4.7.0.0, 4.6.0.1,
4.6.0.0, 4.5.1.0, 4.5.0.0, 4.4.1.0, 4.4.0.0, 4.3.1.0, 4.3.0.0, 4.2.0.2,
4.2.0.1, 4.2.0.0, 4.1.0.0, 4.0.0.0, 3.0.3.2, 3.0.3.1 (global constraint
requires installed instance)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

**Comment by acowley** [comment]
I'd like to do so, actually. If you can figure out what constraints need to be relaxed to get it to build, I'll accept a PR.

There may be some issues with `Prelude` including `Applicative` or not.
