### ISSUE TITLE
CoRec as extendible open Union

### ISSUE THREAD

**Issue by noinia** [acowley/Frames#28]
I'm (planning on) using Frames' CoRecs as an extendible open union. My use case also involves pattern matching on a CoRec. I've written a few simple functions that allow me to pattern match on a coRec with something like: 

```haskell
foo = match myCoRec $ 
            H (\NoIntersection -> "No Intersection")
         :& H (\(x :: Int)     -> show x)
         :& RNil
 ```
See [this gist](https://gist.github.com/noinia/9bcc520b5abec1d3d298) for details (the gist also defines a 'asA' function to easily extract a Maybe value from a CoRec). Adding something to Frames.CoRec might be useful to others as well. 

Ideas for improvements on how to do this are welcome as well of course :).

**Comment by acowley** [comment]
I commented on the gist, but, just to be clear, this is totally awesome and should definitely be included. Can you make a PR?

**Comment by noinia** [comment]
Yes, I'll do that. I guess the best place to add them would be Frames.Rec, since that module deals with 'CoRec Identity''s? I think something like this might also be possible for arbitrary 'CoRec f''s (with something like `Handler f b a = f a -> b'. I'll see if I can get that to work, while retaining a simple Syntax for the CoRec Identity case. If that works I'll add them to Frames.DoRec
