### ISSUE TITLE
Can't run demos

### ISSUE THREAD

**Issue by danse** [acowley/Frames#30]
Maybe a duplicate of #23, except that i can follow the steps and install everything, but i get an error when trying to run the demos:

```
 Frames (master)*$ cabal run plot
Preprocessing library Frames-0.1.0.0...
In-place registering Frames-0.1.0.0...
Preprocessing executable 'plot' for Frames-0.1.0.0...

demo/Plot.hs:4:8:
    Could not find module ‘Diagrams’
    Use -v to see a list of the files searched for.
 Frames (master)*$ 
```

**Comment by acowley** [comment]
It's probably a `cabal configure` issue. Just to be sure, can you try running,

```
cabal clean
cabal configure -f demos
cabal run plot
```

**Comment by danse** [comment]
Sure:
```
 Frames (master)$ cabal clean
cleaning...
 Frames (master)$ cabal configure -f demos
Resolving dependencies...
Configuring Frames-0.1.0.0...
 Frames (master)$ cabal run plot
Preprocessing library Frames-0.1.0.0...
[ 1 of 14] Compiling Frames.ColumnTypeable ( src/Frames/ColumnTypeable.hs, dist/build/Frames/ColumnTypeable.o )

... omitting a bunch of compilations here ...

[14 of 14] Compiling Frames           ( src/Frames.hs, dist/build/Frames.o )
In-place registering Frames-0.1.0.0...
Preprocessing executable 'plot' for Frames-0.1.0.0...

demo/Plot.hs:4:8:
    Could not find module ‘Diagrams’
    Use -v to see a list of the files searched for.
 Frames (master)$ 
```

**Comment by danse** [comment]
```
 Frames (master)$ cabal --version
cabal-install version 1.20.0.3
using version 1.20.0.2 of the Cabal library 
 Frames (master)$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.3
```

**Comment by danse** [comment]
I was not able to run the example in the tutorial as well ... `Frames` is cool and i am looking forward to use it, but it is probably too much at an early stage for an Haskell beginner like me :)

I will keep an eye on this project!

By the way, what are your opinion on the alternatives? I think that the only ones are HMatrix and Numerical, right?

**Comment by acowley** [comment]
Okay, I'm willing to help figure out why it's not working for you, but I understand if you don't have time. It does seem like a cabal issue, so running with `-v` would be the next step if you get a chance.

**Comment by danse** [comment]
Sure, i can find time if you want to fix this, i just thought that it was not a wise task for a beginner. I tried:

    cabal run -v plot
    cabal -v run plot
    cabal run plot -v

But i always get:
```
 demo/Plot.hs:4:8:
    Could not find module ‘Diagrams’
    Use -v to see a list of the files searched for.
```
As a result of the script. So probably the output is produced by some other script which is wrapped in the Cabal command, and which does not get command line options correctly forwarded

**Comment by acowley** [comment]
Oof, that will make it harder to track down. I'm not sure why the verbose output isn't working; that doesn't seem like a very old version of `cabal-install` so I'd expect more output.

**Comment by danse** [comment]
Allright, here for some attempts i did, they could be useful. I looked for a way to run an interactive interpreter in a sandbox, and i found `cabal repl`. Exactly what i needed for debugging!

I tried:

```
$ cabal repl
*Frames> import Diagrams

<no location info>:
    Could not find module ‘Diagrams’
    It is not a module in the current program, or in any known package.
```
I looked into `.cabal-sandbox/lib/x86_64-osx-ghc-7.8.3/`, and there are indeed a bunch of packages related to diagrams:
```
drwxr-xr-x   5 francesco  staff  170 Jun  1 16:23 diagrams-core-1.2.0.6/
drwxr-xr-x   5 francesco  staff  170 Jun  1 16:24 diagrams-lib-1.2.0.9/
drwxr-xr-x   6 francesco  staff  204 Jun  1 16:24 diagrams-postscript-1.1.0.5/
drwxr-xr-x   7 francesco  staff  238 Jun  1 16:24 diagrams-rasterific-0.1.0.8/
drwxr-xr-x   6 francesco  staff  204 Jun  1 16:25 diagrams-svg-1.1.0.5/
```
I looked at the doc for `diagrams-core` in order to check what can be imported. I was not sure that i could import the topmost `Diagram` symbol. So i tried importing `Diagrams.Core`, and i got:
```
*Frames> import Diagrams.Core

<no location info>:
    Could not find module ‘Diagrams.Core’
    It is a member of the hidden package ‘diagrams-core-1.2.0.6’.
    Perhaps you need to add ‘diagrams-core’ to the build-depends in your .cabal file.
```
If i add `diagrams-core` to `build-depends`, i can successfully import it in the interpreter, but the demo is still trying to import just `Diagrams`, and it will not work

**Comment by acowley** [comment]
Thanks, that is helpful! In general you'd want to pass `cabal repl` the name of a build target like `plot` so that it uses the right `build-depends` section. The newest `Frames` here in the repository also uses newer versions of the various `diagrams` packages, so that may be causing an issue.

**Comment by danse** [comment]
> In general you'd want to pass cabal repl the name of a build target like plot so that it uses the right build-depends section

When i do that, i get the usual:
```
demo/Plot.hs:4:8:
    Could not find module ‘Diagrams’
    Use -v to see a list of the files searched for.
Failed, modules loaded: none.
```

> The newest Frames here in the repository also uses newer versions of the various diagrams packages, so that may be causing an issue

Sure, a version mismatch could bring a lot of problems, but what do you mean by *here in the repository*? I cloned a recent version, my last commit is 637ee35c5ed64f238bab4492541fb25e759667af. The version specified in the cabal file should correspond with the one which is expected

**Comment by danse** [comment]
Now i see what you mean, no specific version is pinned in the cabal file. I will try to install the latest version of Diagrams

**Comment by danse** [comment]
When i remove the sandbox, update Cabal and try again, i find the same error described in #23. So this was happening because i had an outdated Cabal package index, which caused the installation of Diagrams 1.2. Thanks for your help!

**Comment by acowley** [comment]
Thank you so much for having the patience to work through this! As you noticed, we're at an unfortunate intermediate state with the diagrams dependencies, so I've not locked anything down. I should have suspected that as the issue from the start.

**Comment by danse** [comment]
Thanks to you!
