### ISSUE TITLE
filtering an in memory frame

### ISSUE THREAD

**Issue by cocreature** [acowley/Frames#31]
The tutorial mentions filtering but that relies on the pipes library which obviously only makes sense when using the streaming version using producers. I couldn't figure out a way to filter an in memory frame. I am sure I am missing something, but I am not quite sure what.

**Comment by acowley** [comment]
We should add a helper for making it easier. But we have to make sure we think through the details of sharing to make sure the most useful API is exposed most visibly.

I think the current setup allows you to go through the `Foldable` instance to stream a `Frame` into a `Pipe`, filter it there, and build up a new `Frame`, but I don't think I've actually tried to write that bit of code.

**Comment by cocreature** [comment]
Ah that makes sense, for the record, here's the ugly solution I came up with after your tip
```
virginica :: Frame Iris -> IO (Frame (Iris))
virginica f = inCoreAoS $ (conv f) >-> P.filter ((==Virginica) . view species)
```
I'll leave the issue open as you said, that there should be a helper for doing this nicely.

**Comment by acowley** [comment]
I haven't figured out any particularly "right" solution to this yet.

Ultimately, I think the way you've done it here is fine, but I think I'd do it in ST and offer a pure interface. Any thoughts on the naming? There is no real naming convention within `Frames`, so I'd be tempted to call it something like `filterFrame` to avoid needing qualified imports just for the one thing.

**Comment by cocreature** [comment]
`filterFrame` is fine with me.

**Comment by codygman** [comment]
@acowley @cocreature I made this helper to generalize this:

```haskell
onFrame :: (RecVec rs, PrimMonad m) =>  Pipe (Record rs) (Record rs) m () -> FrameRec rs -> m (FrameRec rs)
onFrame pipe f = inCoreAoS $ P.each f P.>-> pipe
```
