### ISSUE TITLE
MissingData has no main method

### ISSUE THREAD

**Issue by cocreature** [acowley/Frames#32]
The `missing` executable specifies the `MissingData` module as `main-is`. However that module doesn't contain a main method. How is this supposed to work?

**Comment by acowley** [comment]
That's something I've done to make cabal happy so I have a build target I can give to `cabal repl` or `haskell-mode`. I've only ever run that code in GHCi, not built a standalone executable, so I never wrote a `main`.

I can see how this is confusing; do you have a suggestion for how to clarify it? Maybe just some comments in the `MissingData` module?

**Comment by cocreature** [comment]
The problem is that when configuring with -f demos and then building (in my case using stack, but I don't think cabal behaves any differently here), it will obviously fail because of that. If you only need the code and not an executable, isn't that exactly what a library is for?

**Comment by acowley** [comment]
I think you can only have one library target in a package.

**Comment by cocreature** [comment]
Ah damnit, you're right. I guess one option would be to extract all the demos into a separate project. It feels kinda wrong to not being able to build when configuring with -f demos.

**Comment by cocreature** [comment]
Thanks.

**Comment by acowley** [comment]
Yeah, you're completely right. I just never run into this due to my weird workflow.
