### ISSUE TITLE
Bug in instance Monoid Frame

### ISSUE THREAD

**Issue by dalejordan** [acowley/Frames#36]
Instead of:

     Frame l1 f1 `mappend` Frame l2 f2 = Frame (l1+l2) $ \i ->
                                          if i < l1 then f1 i else f2 i

I think you want:

     Frame l1 f1 `mappend` Frame l2 f2 = Frame (l1+l2) $ \i ->
                                          if i < l1 then f1 i else f2 (i - l1)

**Comment by acowley** [comment]
You're right! Want to turn this into a PR?

**Comment by dalejordan** [comment]
Done.
