### ISSUE TITLE
Stackage?

### ISSUE THREAD

**Issue by sid-kap** [acowley/Frames#43]
Do you have any plans to add Frames to Stackage?
I'm very new to this, but I would be willing to help if there's something I could do to help.

I believe it might be as easy as forking github.com/fpgo/stackage and adding the following to build-constraints.yaml:

```
"Anthony Cowley acowley@gmail.com @acowley":
    - Frames
```

I don't mind making the PR to fpgo/stackage, if you give me permission.

By the way, thanks for all your hard work on Frames! I've really enjoyed using it so far.

**Comment by acowley** [comment]
Thanks for the nudge, this is a good idea. I'll make the PR when I get some keyboard time just to make sure there's no confusion.

**Comment by acowley** [comment]
I [made the PR](https://github.com/fpco/stackage/pull/1151). Hopefully there won't be any hiccups; I'll update again when there's progress.

**Comment by acowley** [comment]
It is merged! Thanks again for the reminder to do this.
