### ISSUE TITLE
Newest version of readable has removed instance for Text

### ISSUE THREAD

**Issue by boothead** [acowley/Frames#6]
https://github.com/mightybyte/readable/commit/bfc10744c8b74001968fd6cb54919b3b13bdcd3e

This seems to the latest version on hackage. I'll try and submit a patch in the next day or so.

**Comment by acowley** [comment]
It seems the only choices are to provide an orphan instance for Text or just use our own `Readable` class. I'd lean towards the latter as I don't see a huge amount of value in taking advantage of a larger universe of Readable instances out there. Any thoughts?

**Comment by acowley** [comment]
Doug put back the instance we need, so everything should be good to go with the latest `Readable`!

https://github.com/mightybyte/readable/commit/bfc10744c8b74001968fd6cb54919b3b13bdcd3e#commitcomment-9638780
