### ISSUE TITLE
tableTypes should conditionally create type synonym

### ISSUE THREAD

**Issue by codygman** [acowley/Frames#60]
Say I have 2 csvs with these headers:

```
manager,age,pay

employee,age,pay
```

tableTypes will fail if I try to use it for both of them.

Could tableTypes conditionally create type synonyms here to make this work?

**Comment by acowley** [comment]
The way it is now, ones options are to tell frames to add a particular prefix to all generated column names, or to explicitly name the columns oneself, ignoring any file header.

Your suggestion is that we re-use an existing synonym if an identical definition already exists?

**Comment by codygman** [comment]
@acowley Yes.

To add to this a bit:

#Managers
```
id,manager,age,pay
0,Joe,53,"80,000"
1,Sarah,44,"80,000"
```
#Employees
```
id,employee,age,pay,manager_id
2,Sadie,28,"40,000",0
3,Tom,25,"40,000",1
```
**Desired Result**:

#EmployeesWithManagerInfo
```
id,employee,manager
2,Sadie,Joe
3,Tom,Sarah
```
So I'd define TableTypes for both `#Managers` and `#Employees`. One thing I'd want to do is then create `#EmployeesWithManagerInfo` based on the shared Id field between the `#employee` and `#manager` fields.

Another thing would be if I wanted a function that simply printed the id. If both `#Employee` and `#Manager` share Id, I only have to create one function to print Id's for them or any other future vinyl record that uses the Id column

Perhaps this makes it more clear?

**Comment by acowley** [comment]
Yeah, this ought to be supported. I thought I had some work on table joins somewhere, but I can't find it now. I'm not entirely certain how to deal with duplicate definition detection yet:

- Can we check (via TH) if an identical definition is already in scope? 
- Or would we have to generate the types for both tables in one shot (e.g. `tableTypes ["managers.csv", "employees.csv"]...`)?

I'll need to look into it. Let me know if you have a chance to figure out how to do the first option.

**Comment by codygman** [comment]
Checking via TH if an identical definition is already in scope is my first approach. I'll see if I can find anything.

Table joins, grouping, and other relational stuff is the primary reason for my interest in Frames right now.

My dream is being able to have a fully generic join function that when given a column for the left table, only requires an Eq instance for the right join column. It's quite exciting to think of the possibilities of melding together ad-hoc analysis and static typing.

**Comment by codygman** [comment]
I'm thinking [lookupTypeName](http://hackage.haskell.org/package/template-haskell-2.11.0.0/docs/src/Language.Haskell.TH.Syntax.html#lookupTypeName) might be what is needed.

**Comment by acowley** [comment]
Yes, that's a good start. We then need to verify that the definition of the existing thing is identical to what we are about to produce. If the two columns with the same name have different types, we should raise that error at this point.

**Comment by codygman** [comment]
Agreed. I'm going to be  taking another look later I think. I saw a few
examples of using reify with it as well to do something very similar.

**Comment by codygman** [comment]
Just in case I don't figure out how to integrate this with Frames, I figured out how to solve the problem [in this repo](https://github.com/codygman/th-upsert-typesynonym/blob/8ecf7437ec004a8870c8d9d891d9626769def613/src/TH.hs)
