### ISSUE TITLE
Bad type inference for text column.

### ISSUE THREAD

**Issue by rustydc** [acowley/Frames#86]
I tried loading ggplot2's [mpg.csv dataset](https://forge.scilab.org/index.php/p/rdataset/source/tree/master/csv/ggplot2/mpg.csv) with `tableTypes "Mpg" "data/mpg.csv"`, and the `drv` column shows up as `["drv" :-> Int]`, even though most of the rows are "f" or "r".  This seems to cause 131 of the 235 rows to be silently dropped when loaded.

**Comment by acowley** [comment]
Thanks for the report, and sorry it took so long to get to. I had apparently left the repo mid-merge with other large changes and wanted to push everything through. I'll sort out new Hackage releases shortly.
