### ISSUE TITLE
I seem to be running into unmanaged dependencies. 

### ISSUE THREAD

**Issue by michaelochurch** [acowley/Frames#9]
I'm trying to go through the tutorial, line by line, that is linked here: https://github.com/acowley/Frames/blob/master/demo/Tutorial.hs

I've run cabal configure, build, and install in the main directory, after which the cabal repl has no problem compiling Frames:

    pwnmachine $ cabal repl
    Preprocessing library Frames-0.1.0.0...
    GHCi, version 7.8.3: http://www.haskell.org/ghc/  :? for help
    Loading package ghc-prim ... linking ... done.
    Loading package integer-gmp ... linking ... done.
    [...]
    Loading package pipes-4.1.4 ... linking ... done.
    [ 1 of 13] Compiling Frames.TypeLevel ( src/Frames/TypeLevel.hs, interpreted )
    [ 2 of 13] Compiling Frames.CoRec     ( src/Frames/CoRec.hs, interpreted )
    [...]
    [13 of 13] Compiling Frames           ( src/Frames.hs, interpreted )
    Ok, modules loaded: Frames, Frames.Col, Frames.ColumnTypeable, Frames.ColumnUniverse, Frames.CoRec, Frames.CSV, Frames.Exploration, Frames.Frame, Frames.InCore, Frames.Rec, Frames.RecF, Frames.RecLens, Frames.TypeLevel.
    *Frames>

Unfortunately, there are a number of modules mentioned in the Demo that seem not to be included as dependencies. For example, I run into:

    *Frames> import qualified Control.Foldl as L
     <no location info>:
         Could not find module ‘Control.Foldl’
         It is not a module in the current program, or in any known package.
     *Frames> import Lens.Family
     <no location info>:
        Could not find module ‘Lens.Family’
        It is not a module in the current program, or in any known package.

Please let me know if you need any other information on my installation or process. It's quite possible that there's something that I'm not doing right. 

At any rate, I'm really excited to see this library and can't wait to start using it. Frames itself seems to work fine. It's just that I'm not able to run the tutorial because it seems to have unlisted dependencies.

**Comment by acowley** [comment]
Try specifying the `tutorial` target: `cabal repl tutorial`

To install dependencies, you'll want to specify the `demos` flag (eg, `-f demos`).

**Comment by michaelochurch** [comment]
Thanks!

This may not be blocking for use of Frames, but it's an error that I got in the install process that you may want to know about. (Again, it may mean that I'm doing something wrong.)

    pwnmachine $ cabal install -f demos
    Resolving dependencies...
    In order, the following will be installed:
    Boolean-0.2.3 (new package)
    JuicyPixels-3.2.2 (new package)
    [...]
    Warning: Note that reinstalls are always dangerous. Continuing anyway...
    Notice: installing into a sandbox located at
    /Users/michaelchurch/haskell/Frames/.cabal-sandbox
    Downloading Boolean-0.2.3...
    [...]
    Loading package Chart-diagrams-1.3.3 ... linking ... done.

    demo/Plot.hs:1:1:
         Exception when trying to run compile-time code:
           data/trigly_d.csv: openFile: does not exist (No such file or directory)
        Code: tableTypes "Trigly" "data/trigly_d.csv"
     cabal: Error: some packages failed to install:
     Frames-0.1.0.0 failed during the building phase. The exception was:
     ExitFailure 1

**Comment by acowley** [comment]
Yeah, I should write up some notes on how to approach the demos and tutorial. I generally don't intend such executables to be installed. Rather, they're there to play with in the REPL or `cabal run` without installing. What you hit there is a missing data file used by a demo program. To fix it, we'd have to make a more complicated `Setup.hs`, but the right thing is to just not install them.

So, install `--dependencies-only` in the sandbox, then run the "get data" target, then run demo program targets or load them into the REPL. I'll put words to that effect in the README.

**Comment by michaelochurch** [comment]
Thanks! I seem to be running into a new problem. I imagine that I'll be able to figure it out on my own (I'm still learning Cabal) but here it is:

    cabal: Cannot build the executable 'getdata' because the component is marked
as disabled in the .cabal file.

So I looked into ```Frames.cabal```, and it seems to disable the executables based on the absence of a flag called ```demos```. Do you know of any good Cabal references that would give me pointers on how to (among other things) set flags and, in general, interpret the .cabal file for a large project?

Thanks so much!

**Comment by acowley** [comment]
No doubt it's confusing! You should run `cabal configure -f demos` before `cabal run getdata`. This is in the README, but it's easy to miss because it's part of a larger command.

I suppose [this](https://www.haskell.org/cabal/users-guide/installing-packages.html#controlling-flag-assignments) is the official reference.

**Comment by michaelochurch** [comment]
Seems to have worked. Thanks!

**Comment by michaelochurch** [comment]
One minor note: in the README, you advise attaching ```-f demos``` to the ```cabal install``` rather than the ```cabal configure```. Is that an error, or should both work?

I ran through the ```README.md``` directions after making some changes to my environment and it didn't work. Adding ```-f demos``` to the ```cabal configure``` did work.

**Comment by acowley** [comment]
I'll try it again. I thought it worked okay on that dependency only installation line.
