### ISSUE TITLE
Re-add to Stackage Nightly

### ISSUE THREAD

**Issue by pepeiborra** [acowley/Frames#90]
The Frames package is [disabled](https://github.com/fpco/stackage/blob/409794022a0e81b1796eb228c521a086bed32371/build-constraints.yaml#L2598) in Stackage Nightly because the tests don't compile. I believe this is not true anymore, is there any other reason to not re-add it ?

**Comment by acowley** [comment]
Thanks for keeping up on this. I opened the [PR](https://github.com/fpco/stackage/pull/2930).

**Comment by mihaimaruseac** [comment]
Unfortunately, the tests on Stackage are still failing

```haskell
Building test suite 'mpg' for Frames-0.2.1..
[1 of 1] Compiling Main             ( test/Mpg.hs, dist/build/mpg/mpg-tmp/Main.o )

test/Mpg.hs:1:1: error:
    Exception when trying to run compile-time code:
      test/data/mpg.csv: openFile: does not exist (No such file or directory)
    Code: tableTypes "Mpg" "test/data/mpg.csv"
  |
1 | {-# LANGUAGE DataKinds, FlexibleContexts, TemplateHaskell, TypeOperators #-}
  | ^
```

**Comment by mihaimaruseac** [comment]
Tests are passing, Frames added back to Stackage
