### ISSUE TITLE
quoting in custom type

### ISSUE THREAD

**Issue by dmvianna** [acowley/Frames#95]
I am having an unexpected issue with parsing a custom type. Frames parses the data correctly if I use its default parsers, and my parser also parses correctly the same `Text` input that is returned by Frames' `Text` parser. However, when I try to use my own parser (expecting Frames will use it within the columns it found), it stops at the first `,` of the input.

**Input**
```csv
"1992010803","ABSTRACT (11 Document No. AU-A-10803/92 (19) AUSTRALIAN PATENT OFFICE (54) Title FILM CARTRIDGE BAR CODE SCANNER AND CONTROLLER FOR A DIGITAL IMAGING SYSTEM International Patent Classification(s) (51) 5 G03B007/24 G06K009/18 (21) Application No. 10803/92 (22) Application Date 06.02.92 Priority Data (31) Number (32) Date (33) Country 656605 19.02.91 US UNITED STATES OF AMERICA (43) Publication Date 27.08.92 (71) Applicant(s) MINNESOTA MINING AND MANUFACTURING COMPANY (72) Inventor(s) RICHARD RANDALL LEMBERGER; TERRENCE HAROLD JOYCE (74) Attorney or Agent SPRUSON FERGUSON, GPO Box 3898, SYDNEY NSW 2001 (57) Claim 1. A laser imaging system, comprising: a cartridge of photographic film; a machine readable information bearing medium associated with the cartridge and including information characterizing the cartridge and/or film; a laser imager, including: a cartridge receiving mechanism; a laser scanning system including a laser for imaging the film; and a reading device for reading the information from the information bearing medium; and an image management system responsive to image input data and coupled to the laser imager, for controlling the laser imager as a function of the input data and the information read from the information bearing medium. I I"
"1992010803","Claim 1. A laser imaging system, comprising: a cartridge of photographic film; a machine readable information bearing medium associated with the cartridge and including information characterizing the cartridge and/or film; a laser imager, including: a cartridge receiving mechanism; a laser scanning system including a laser for imaging the film; and a reading device for reading the information from the information bearing medium; and an image management system responsive to image input data and coupled to the laser imager, for controlling the laser imager as a function of the input data and the information read from the information bearing medium."
```

**My parser**
```haskell
λ> a <- loadPat
λ> mapM_ print (take 2 (F.toList a))
{id :-> 1992010803, abstract :-> NoAddress (ErrInfo {_errDoc = (interactive):1:578: error: unexpected
    EOF, expected: "g", "p"
<lemberger; terrence harold joyce (74) attorney or agent spruson ferguson<EOF> 
                                                                         ^     , _errDeltas = [Columns 577 577]})}
{id :-> 1992010803, abstract :-> NoAddress (ErrInfo {_errDoc = (interactive):1:33: error: unexpected
    EOF, expected: "g", "p"
"claim 1. a laser imaging system<EOF> 
                                ^     , _errDeltas = [Columns 32 32]})}
```

The [project](https://github.com/dmvianna/patents/tree/bc20be3773bc8f968eba7abc0ec90fc1464af47a) is small, as I'm figuring out how to parse addresses from a real world public free text dataset. This is a good example of the kind of problem I tackle at work with `Python` and `regex`, but that I would love to transfer to `Haskell` and `trifecta`, using a streaming algorythm so I can tackle bigger data.

**Comment by acowley** [comment]
I hope I've figured this out. It was a confusing error, but a clue I followed was,

```haskell
*Patents> :info PA
type PA =
  Record
    '["id" Frames.Col.:-> Int, "abstract" Frames.Col.:-> Address]
```

But the data looked like it should be an `abstract` (or `Text`). The problem was that `Address` was not failing to parse in a helpful way. I changed the code to this,

```haskell
instance Readable Address where
  fromText t =
    case
      parseByteString poboxAddress mempty (
      (encodeUtf8 . T.toCaseFold) t) of
      Success x -> pure x
      Failure e -> mzero
```

And then it looks like `loadPat` is giving something more sensible. 

There is still an annoying bit: the header row in the data file is being interpreted as a data row. This is because when column names are given in the source code, the assumption is that this is because the CSV does not have a header row. In this case, you are simply overriding the column names in the data file.

I don't know if we can get that guess work right every time. Perhaps the right thing to do is to let something like `readTableOpt` take a CSV line `Producer` (similar to [this issue](https://github.com/acowley/Frames/issues/92)). For the time being, manually removing the header line yourself is the easiest fix.

My opinion is that a bit of manual fixup with the header line in particular is probably easier than dealing with all possible situations on the `Frames` side, but I'd like to be wrong about that. The concern, as mentioned in that Issue, is that we do the type inference on that file. We would have to expose enough flexibility on the `TemplateHaskell` side to also enable the use of something like a `Producer` there (so you could similarly strip off the first line before the column type inference machinery goes to work). So the choice is to allow manipulation of the data file at both compile and runtime on the Haskell side, or do a bit of data sanitation as a separate, one-time step.

**Comment by dmvianna** [comment]
Yes, but then I don't get to extract `Address`es, which is what I need to do. How would you go about that?

**Comment by dmvianna** [comment]
Thanks, that's exactly what I was looking for! However, my parser is still failing on the commas. I get no valid addresses. I wonder if we're using different library versions. If you're using `stack`, could you show the output of `stack list-dependencies`? My results are
```
Cabal 1.24.2.0
Frames 0.1.9
HUnit 1.5.0.0
MonadRandom 0.5.1
QuickCheck 2.9.2
StateVar 1.1.0.4
adjunctions 4.3
ansi-terminal 0.6.3.1
ansi-wl-pprint 0.6.7.3
array 0.5.1.1
async 2.1.1.1
attoparsec 0.13.1.0
base 4.9.1.0
base-orphans 0.5.4
bifunctors 5.4.2
binary 0.8.3.0
blaze-builder 0.4.0.2
blaze-html 0.8.1.3
blaze-markup 0.7.1.1
bytestring 0.10.8.1
cabal-doctest 1.0.2
cabal-helper 0.7.3.0
call-stack 0.1.0
charset 0.3.7.1
clock 0.7.2
cmdargs 0.10.17
comonad 5.0.1
containers 0.5.7.1
contravariant 1.4
cpphs 1.20.8
deepseq 1.4.2.0
directory 1.3.0.0
distributive 0.5.2
djinn-ghc 0.0.2.3
djinn-lib 0.0.1.2
either 4.4.1.1
exceptions 0.8.3
extra 1.5.3
fail 4.9.0.0
fclabels 2.0.3.2
filepath 1.4.1.1
fingertree 0.1.1.0
foldl 1.2.5
free 4.12.4
ghc 8.0.2
ghc-boot 8.0.2
ghc-boot-th 8.0.2
ghc-mod 5.7.0.0
ghc-paths 0.1.0.9
ghc-prim 0.5.0.0
ghc-syb-utils 0.2.3.2
ghci 8.0.2
hashable 1.2.6.1
haskell-src-exts 1.18.2
hlint 1.9.41
hoopl 3.10.2.1
hpc 0.6.0.3
hscolour 1.24.1
hspec 2.4.3
hspec-core 2.4.3
hspec-discover 2.4.3
hspec-expectations 0.8.2
integer-gmp 1.0.0.1
integer-logarithms 1.0.1
kan-extensions 5.0.2
lens 4.15.1
math-functions 0.2.1.0
microlens 0.4.8.0
mmorph 1.0.9
monad-control 1.0.2.1
monad-journal 0.7.2
mtl 2.2.1
mwc-random 0.13.6.0
old-locale 1.0.0.7
old-time 1.1.0.3
optparse-applicative 0.13.2.0
parallel 3.2.1.1
parsec 3.1.11
parsers 0.12.5
patents 0.1.0.0
pipes 4.3.4
polyparse 1.12
prelude-extras 0.4.0.3
pretty 1.1.3.3
primitive 0.6.1.0
process 1.4.3.0
profunctors 5.2
quickcheck-io 0.1.4
random 1.1
raw-strings-qq 1.1
readable 0.3.1
reducers 3.12.1
refact 0.3.0.2
reflection 2.1.2
rts 1.0
safe 0.3.15
scientific 0.3.5.1
semigroupoids 5.1
semigroups 0.18.2
setenv 0.1.1.3
split 0.2.3.2
stm 2.4.4.1
syb 0.6
tagged 0.8.5
template-haskell 2.11.1.0
temporary 1.2.1
text 1.2.2.1
tf-random 0.5
time 1.6.0.1
transformers 0.5.2.0
transformers-base 0.4.4
transformers-compat 0.5.1.4
trifecta 1.6.2.1
uniplate 1.6.12
unix 2.7.2.1
unordered-containers 0.2.8.0
utf8-string 1.0.1.1
vector 0.11.0.0
vector-th-unbox 0.2.1.6
vinyl 0.5.3
void 0.7.2
```

Alternatively, if you sent me a push request, that could give me clues as to what is different in your code. Mine compiles perfectly, but I only get

```haskell
λ> runEffect $ patStreamM >-> P.take 2 >-> P.print
{Just id :-> "1992010803", Nothing}
{Just id :-> "1992010803", Nothing}
```

**Comment by dmvianna** [comment]
**UPDATE** It works! But not with the latest LTS stackage resover `LTS-9.13`. I used the latest `Frames` as in my fork of this repository (7df982f8f6760fe32271c4bb65ece0f1a0bff33b + stack.yaml). So there, it was indeed a problem with versioning. Regardless, I'm very thankful to you for showing me how you would approach this problem.

**Comment by acowley** [comment]
Oh, no, that's annoying! As it happens I was testing against LTS-9.13 rather than nightly because, inexplicably, ghc-8.2.1 is broken on darwin in nixpkgs at this very moment. Thank you for fighting through that!
