### ISSUE TITLE
encoding

### ISSUE THREAD

**Issue by dmvianna** [acowley/Frames#96]
Hi, Andrew.

```haskell
λ> printValidAddresses
{id :-> "1992010803", abstract :-> POBoxAddress "3898" "sydney" "nsw" "2001"}
{id :-> "1992010807", abstract :-> POBoxAddress "4164" "sydney" "nsw" "2001"}
{id :-> "1999042444", abstract :-> POBoxAddress "1285" "k,melbourne" "vic" "3001"}
*** Exception: ../data/IPGOD.IPGOD122B_PAT_ABSTRACTS.csv: hGetLine: invalid argument (invalid byte sequence)
```
How would one change the encoding prior to parsing a CSV file? I thought of [decodeLatin1](http://hackage.haskell.org/package/text-1.2.2.2/docs/Data-Text-Lazy-Encoding.html#v:decodeLatin1), but there isn't an obvious place to put it.

[current commit](https://github.com/dmvianna/patents/tree/6f5b71cdd1470ac2515cc33a37f0e717207a6147)

**Comment by acowley** [comment]
I can't reproduce, but I don't think you're using the same data file as is in your repository. The [file there](https://github.com/dmvianna/patents/blob/6f5b71cdd1470ac2515cc33a37f0e717207a6147/data/pat_abstracts.csv) has no record with id 1999042444, for example.

**Comment by dmvianna** [comment]
I’m not using the same file. I didn’t want to include a massive text file in the repo. I can get a `head` of the file including the offending line or the whole thing, which do you think is the best approach?

-- 
Daniel Vianna

**Comment by dmvianna** [comment]
Munging files from external stakeholders is what I do for a living. I would think the most convenient approach would be to stream the file in one pass. It would be great if we could do that with `pipes`, that is, translate the encoding and then get `Frames` to break it into columns and types.

I’ll work on the `head` and the `Text` once I’m on the train going to work. That should be an hour or two away.

-- 
Daniel Vianna

**Comment by acowley** [comment]
Okay, end should incorporate this [machinery](http://hackage.haskell.org/package/pipes-text-0.0.2.5/docs/Pipes-Text-Encoding.html) at compile- and run-time.

**Comment by dmvianna** [comment]
The offending line is now in the file, and the code points to it. Please see if you can [reproduce](https://github.com/dmvianna/patents/tree/18c7df9c423227b41e2d092c52e11bb0e3deb295). As a side note, I'm testing it on a Mac, but last Friday this ran perfectly fine in Windows 10. However I will not be able to reproduce it in Windows, as I had to make many changes to my Haskell setup there.

**Comment by acowley** [comment]
The below modification of your program now works with the [pipe-everything branch](https://github.com/acowley/Frames/tree/pipe-everything) of `Frames`! We should poke at that branch a bit more before merging it into master since it's a pretty large change, but I'm hoping it also addresses #77 and #92, though I did a poor job of incorporating the start offered in #93, so I'm not sure if the current changes cover everyone's needs.

```haskell
{-# LANGUAGE ConstraintKinds   #-}
{-# LANGUAGE DataKinds         #-}
{-# LANGUAGE FlexibleContexts  #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes       #-}
{-# LANGUAGE TemplateHaskell   #-}
{-# LANGUAGE TypeFamilies      #-}
{-# LANGUAGE TypeOperators     #-}
{-# OPTIONS_GHC -Wall #-}

module Patents where

-- import           Lens.Micro            ((%~), (^.))
import           Pipes                 (Producer, (>->))
import qualified Pipes.Prelude         as P

import           Data.Vinyl            (Rec)
import           Frames                (runSafeEffect, (:->), Text, MonadSafe)

import           Frames.CSV            (declareColumn,
                                        pipeTableMaybe, readFileLatin1Ln)

import           Frames.Rec

import           PatAbstracts

declareColumn "patId" ''Text
declareColumn "abstract" ''Address
type PatColumns = '["id" :-> Text, "abstract" :-> Address]
type PA = Record PatColumns
type PAMaybe = Rec Maybe PatColumns

patStreamM :: MonadSafe m => Producer PAMaybe m ()
patStreamM =  readFileLatin1Ln "data/pat_abstracts.csv" >-> pipeTableMaybe

printValidAddresses :: IO ()
printValidAddresses =
  runSafeEffect $ patStreamM >-> P.map recMaybe >-> P.concat >-> P.print 
```

**Comment by dmvianna** [comment]
I love it, Anthony! Works for me, and being modular, we could change the input and keep the rest. Would that work with things like http streams, at least conceptually?

**Comment by acowley** [comment]
Yes, I think so!

A couple things need to happen:

1. We should make this encoding example part of a test suite
2. We need to verify the `pipes` stuff works with row type inference (this involves customizing a `RowGen` record with a custom `Producer`)

After that, I think it'd be great to have an example that pulled the data from a web site. I'm not sure how great an idea that is for the compile-time part, but it'd be neat to show that such a bad idea can be made real! 😃

**Comment by dmvianna** [comment]
Hmm. Did you fix the test suite to build properly yet? And are you available on messaging? I am keen to work on this and learn.

**Comment by acowley** [comment]
Did running the `getdata` program not get the tests working for you?

**Comment by dmvianna** [comment]
Oh wow. `stack exec getdata`. Would you consider a pull request with some trivial documentation for Haskell beginners? Only now I understood how to use the executables. You assume a certain level of familiarity with the Haskell build system (cabal or stack) which will not exist for people first dipping their toe to check if this unknown language might offer something something useful in the real of data analysis.

**Comment by acowley** [comment]
I think across this and the latin1 PR and the initial changes to the README, we've hit the main pieces of this. More documentation is an ongoing effort.
